### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by gnomiik** [imShara/l5p-kbl#1]
First of all, thank you for making this tool! I would love to get it to work. 

But it errors when I run it. Here is an example

(env) [root@legion l5p-kbl] ./l5p_kbl.py breath ffffff --speed 4 --brightness 2
  File "./l5p_kbl.py", line 118
    f"Invalid RGB color model: {color}"
                                      ^
SyntaxError: invalid syntax

**Comment by imShara** [comment]
Try `python3 l5p_kbl.py breath ffffff --speed 4 --brightness 2`

**Comment by gnomiik** [comment]
I just tried this

python3 l5p_kbl.py breath ffffff --speed 4 --brightness 2
  File "l5p_kbl.py", line 118
    f"Invalid RGB color model: {color}"
                                      ^
SyntaxError: invalid syntax

**Comment by imShara** [comment]
Which python version do you use? F-strings required at least 3.6
```
$ python3 -V  
Python 3.9.7
```
Which OS?

**Comment by gnomiik** [comment]
Awesome it works now! I had python 3.5. I upgraded it and it works. Thank you so much for your time to do this project!!
