### ISSUE TITLE
Seeking contact

### ISSUE THREAD

**Issue by DJsushi** [imShara/l5p-kbl#2]
Hello, I'm very sorry I'm contacting you through an issue on GitHub, but I was unable to find another way to contact you. I recently got a Lenovo Legion 5 Pro, and I'm running Linux on it. Are you also running Linux or Windows? If Linux, did you manage to get your 165Hz screen refresh rate to work? You can contact me though email at djsushi123@gmail.com.

Thanks!!

**Comment by imShara** [comment]
It's ok. I'm running L5P on Archlinux / XFCE. Never tried to achieve 165Hz refresh rate. I tried 120Hz on mobile phone, but see no difference except battery lifetime.

**Comment by imShara** [comment]
Check [this](https://www.reddit.com/r/LenovoLegion/comments/miqbv4/comment/hi86sty/?utm_source=share&utm_medium=web2x&context=3) at your own risk.

```
Be sure to enable freesync
To enable freesync create /etc/X11/xorg.conf.d/20-amdgpu.conf
and add the following:

Section "Monitor"
Identifier "eDP"
Modeline "2560x1600_165.00" 777.340 2560 2608 2640 2720 1600 1603 1609 1732 -hsync -vsync
Option "PreferredMode" "2560x1600_165.00"
EndSection
Section "Device"
Identifier "AMD"
Driver "amdgpu"
Option "VariableRefresh" "true"
Option "TearFree" "1"
Option "DRI" "3"
EndSection
```
```
xrandr --newmode "2560x1600_165.00" 777.340 2560 2608 2640 2720 1600 1603 1609 1732 -hsync -vsync
xrandr --output eDP --mode 2560x1600_165.00
```

**But be careful, video can stuck in broken mode even after reboot.** Until hard power reset (I think).

```
I tried adding the "custom resolution" at 165 HZ with xrandr with these commands :

gtf 2560 1600 165
xrandr --newmode "2560x1600_165.00" 1046.03 2560 2792 3080 3600 1600 1601 1604 1761 -HSync +Vsync
xrandr --addmode eDP-1 "2560x1600_165.00"
xrandr --output eDP-1 --mode "2560x1600_165.00"

It lead me to a terrible screen experience with image persistence and screen flickering... On Linux, Windows or at boot time... Which only stopped when I reinitialized the computer the day after ! Don't know why it happened but I'm glad it stopped !
```

**Comment by DJsushi** [comment]
Sorry for the late reply, I'm present again. Thank you very much for your responses. I have an Intel integrated GPU, not AMD. So this fix probably won't work. Also... Would you be able to e-mail me, please? I would like to ask a few more questions about the Lenovo Legion 5 Pro if you have some time to answer. Thanks!!!

My e-mail is djsushi123@gmail.com

**Comment by 123-123-nil** [comment]
I can confirm that creating the below file will put the refresh rate to 165hz.
```
# File: /etc/X11/xorg.conf.d/20-amdgpu.conf
Section "Monitor"
    Identifier "eDP"
    Modeline "2560x1600_165.00" 777.340  2560 2608 2640 2720  1600 1603 1609 1732 -hsync -vsync 
    DisplaySize 345 215
    Option "PreferredMode" "2560x1600_165.00"
EndSection
Section "Device"
     Identifier "amdgpu"
     Driver "amdgpu"
     Option "VariableRefresh" "on"
     Option "DRI" "3"
EndSection
Section "Device"
    Identifier "nvidiagpu"
    Driver "nvidia"
    VendorName "NVIDIA Corporation"
    BoardName "GeForce RTX 3060 Laptop GPU"
    Option "AllowEmptyInitialConfiguration"
    Option "HardDPMS" "on"
EndSection
```

**Comment by imShara** [comment]
> I can confirm that creating the below file will put the refresh rate to 165hz.

Without any issue?

**Comment by 123-123-nil** [comment]
> > I can confirm that creating the below file will put the refresh rate to 165hz.
> 
> Without any issue?

Yes, without any issues. I am daily driving this setup for a month.

I have other issues though with lenovo legion 5 pro

- Wifi hotspot not working
- Brightness control not working in discrete graphics mode
- Weird colors appear while booting. See [this](https://gitlab.freedesktop.org/drm/amd/-/issues/1765)

**Comment by imShara** [comment]
Can confirm all except brightness control. It's not save settings. but works.

Try this to enable discrete video brightness control:


> Discrete mode works on NVIDIA Driver Version: 460.6 with
> ```
> Option "RegistryDwords" "EnableBrightnessControl=1"
> ```
> added to xorg.conf.

**Comment by 123-123-nil** [comment]
Brightness control does work with 460.6 drivers.....

**Comment by 123-123-nil** [comment]
Heyy do u have any microphone issues?

**Comment by imShara** [comment]
> Heyy do u have any microphone issues?

Nope. Which?

**Comment by 123-123-nil** [comment]
If I increase my microphone volume over 30%, all I hear is noise.

**Comment by imShara** [comment]
> If I increase my microphone volume over 30%, all I hear is noise.

Have no problems actually

![mic](https://user-images.githubusercontent.com/4913196/148863390-e4ce9fd5-e507-40df-9d44-db4d6ddeebe2.gif)
.

**Comment by 123-123-nil** [comment]
Brightness control works again with 510 drivers!
